services:
  caddy:
    image: caddy:2
    restart: always
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static_volume:/srv/static:ro
      - media_volume:/srv/media:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
